const PRODUCTS = [
  {id:'denim-90',name:'90s Straight Denim',category:'Jeans',gender:'Unisex',price:96,color:'Vintage wash',image:'assets/denim.jpg',description:'A straight-leg denim with an easy, lived-in shape. Cut from sturdy cotton denim that softens over time without losing its structure.',use:'Made for everyday movement — pair it with a tee, overshirt, or your most worn-in sweater.',details:['100% organic cotton denim','Straight leg, mid rise','Five-pocket construction','Machine wash cold'],badge:'Best seller'},
  {id:'everyday-overshirt',name:'Everyday Overshirt',category:'Jackets',gender:'Unisex',price:118,color:'Charcoal',image:'assets/overshirt.jpg',description:'The layer that earns its place by doing everything. A relaxed overshirt with a clean collar and generous patch pocket.',use:'Wear it as a light jacket, a shirt, or an indoor layer through changing seasons.',details:['Cotton-linen canvas','Relaxed fit','Button front','Two utility pockets'],badge:'Studio favorite'},
  {id:'heavyweight-tee',name:'Heavyweight Studio Tee',category:'T-shirts',gender:'Unisex',price:42,color:'Natural white',image:'assets/tee.jpg',description:'A substantial everyday tee with a soft handfeel and a little more room through the body.',use:'The foundation of a quiet wardrobe. Built for layering, lounging, and long days outside.',details:['100% heavyweight cotton','Boxy fit','Ribbed collar','Pre-washed'],badge:'Essential'},
  {id:'court-01',name:'Court 01 Leather Sneaker',category:'Shoes',gender:'Unisex',price:134,color:'White / Coral',image:'assets/sneakers.jpg',description:'A clean low-top sneaker with a soft leather upper and a subtle coral heel detail.',use:'Your everyday walk-around shoe — comfortable enough for a full day and considered enough for dinner.',details:['Leather upper','Rubber cupsole','Padded footbed','Made in Portugal'],badge:'New'},
  {id:'softline-trouser',name:'Softline Wide Trouser',category:'Trousers',gender:'Women',price:88,color:'Stone',image:'assets/overshirt.jpg',description:'An easy wide-leg trouser with fluid movement and a considered, high-rise waist.',use:'For workdays, travel days, and all the hours between.',details:['Tencel-cotton blend','High rise','Wide leg','Side pockets'],badge:'New'},
  {id:'boxy-poplin',name:'Boxy Poplin Shirt',category:'Shirts',gender:'Women',price:76,color:'Cloud',image:'assets/tee.jpg',description:'A crisp poplin shirt with a softly structured shoulder and a relaxed boxy silhouette.',use:'Wear it open over a tee, tucked into denim, or on its own when the day calls for simplicity.',details:['100% cotton poplin','Boxy fit','Mother-of-pearl buttons','Curved hem'],badge:'Essential'},
  {id:'field-chore',name:'Field Chore Jacket',category:'Jackets',gender:'Men',price:148,color:'Olive charcoal',image:'assets/overshirt.jpg',description:'A durable chore jacket inspired by utility uniforms and refined for everyday wear.',use:'A dependable outer layer for commutes, workshops, and weekends out of town.',details:['Brushed cotton canvas','Relaxed fit','Four front pockets','Reinforced seams'],badge:'New'},
  {id:'relaxed-trouser',name:'Relaxed Taper Trouser',category:'Trousers',gender:'Men',price:92,color:'Washed blue',image:'assets/denim.jpg',description:'A relaxed trouser that narrows gently at the ankle for an easy but polished line.',use:'A go-to alternative to denim when you want a little more ease and intention.',details:['Cotton twill','Mid rise','Tapered leg','Zip fly'],badge:'Everyday'},
  {id:'cloudweight-tee',name:'Cloudweight Tee',category:'T-shirts',gender:'Women',price:38,color:'Soft grey',image:'assets/tee.jpg',description:'An airy, soft tee that feels almost weightless without looking delicate.',use:'For hot afternoons, layered looks, and slow Sundays.',details:['Organic cotton jersey','Relaxed fit','Dropped shoulder','Soft finish'],badge:'Essential'},
  {id:'riviera-low-top',name:'Riviera Low Top',category:'Shoes',gender:'Men',price:124,color:'Ivory',image:'assets/sneakers.jpg',description:'A minimalist low-top with clean lines, a cushioned footbed, and an easy neutral palette.',use:'A daily uniform staple that works with denim, trousers, and everything in between.',details:['Leather and canvas upper','Cushioned footbed','Rubber outsole','Unisex sizing'],badge:'Everyday'},
  {id:'utility-shirt',name:'Cropped Utility Shirt',category:'Shirts',gender:'Women',price:69,color:'Washed black',image:'assets/overshirt.jpg',description:'A cropped utility shirt with a compact shape and purposeful details.',use:'A sharp top layer over dresses, tees, or high-waisted trousers.',details:['Washed cotton','Cropped fit','Chest pocket','Metal snaps'],badge:'New'},
  {id:'washed-denim',name:'Washed Utility Denim',category:'Jeans',gender:'Men',price:104,color:'Light blue',image:'assets/denim.jpg',description:'A relaxed utility jean with a faded wash and a little extra room through the leg.',use:'For days when comfort and character need to show up together.',details:['100% cotton denim','Relaxed fit','Utility pockets','Garment washed'],badge:'Best seller'}
];

function getCart(){return JSON.parse(localStorage.getItem('clothus-cart')||'[]')}
function saveCart(cart){localStorage.setItem('clothus-cart',JSON.stringify(cart)); updateCartCount()}
function addToCart(id){const cart=getCart();const line=cart.find(item=>item.id===id);if(line)line.qty++;else cart.push({id,qty:1});saveCart(cart);showShopNotice('Added to your cart');}
function updateCartCount(){document.querySelectorAll('[data-cart-count]').forEach(el=>{const count=getCart().reduce((sum,line)=>sum+line.qty,0);el.textContent=count;el.hidden=count===0})}
function showShopNotice(text){let n=document.querySelector('.shop-notice');if(!n){n=document.createElement('div');n.className='shop-notice';document.body.appendChild(n)}n.textContent='✓ '+text;n.classList.add('show');setTimeout(()=>n.classList.remove('show'),2200)}
function productCard(product){return `<article class="product-card"><a href="product.html?id=${product.id}" class="product-image"><img src="${product.image}" alt="${product.name}"><span>${product.badge}</span></a><div class="product-info"><div><p class="eyebrow">${product.category} · ${product.gender}</p><h2><a href="product.html?id=${product.id}">${product.name}</a></h2></div><strong>$${product.price.toFixed(2)}</strong></div><button class="text-link add-button" data-add="${product.id}">Add to cart <span>+</span></button></article>`}
function initCatalog(){const grid=document.querySelector('[data-product-grid]');if(!grid)return;const category=document.querySelector('[data-category]'),gender=document.querySelector('[data-gender]'),search=document.querySelector('[data-search]'),count=document.querySelector('[data-product-count]');function render(){const q=(search?.value||'').toLowerCase();const list=PRODUCTS.filter(p=>(category.value==='All'||p.category===category.value)&&(gender.value==='All'||p.gender===gender.value||p.gender==='Unisex')&&(!q||p.name.toLowerCase().includes(q)||p.category.toLowerCase().includes(q)));grid.innerHTML=list.length?list.map(productCard).join(''):'<div class="empty-products"><h2>No pieces found.</h2><p>Try a different filter or search term.</p></div>';count.textContent=`${list.length} pieces`;grid.querySelectorAll('[data-add]').forEach(btn=>btn.addEventListener('click',()=>addToCart(btn.dataset.add)))}[category,gender,search].forEach(el=>el?.addEventListener(el.tagName==='INPUT'?'input':'change',render));render()}
function initProduct(){const mount=document.querySelector('[data-product-detail]');if(!mount)return;const id=new URLSearchParams(location.search).get('id')||PRODUCTS[0].id;const p=PRODUCTS.find(item=>item.id===id)||PRODUCTS[0];mount.innerHTML=`<div class="product-detail-image"><img src="${p.image}" alt="${p.name}"></div><div class="product-detail-copy"><p class="eyebrow">${p.category} · ${p.gender}</p><h1>${p.name}<span class="coral">.</span></h1><p class="product-price">$${p.price.toFixed(2)}</p><p class="detail-description">${p.description}</p><p class="detail-use"><strong>Good for:</strong> ${p.use}</p><div class="detail-rule"></div><p class="detail-label">Color · <strong>${p.color}</strong></p><ul class="detail-list">${p.details.map(d=>`<li>${d}</li>`).join('')}</ul><button class="button coral-button" data-add="${p.id}">Add to cart <span>→</span></button><a class="back-link" href="products.html">← Back to all pieces</a></div>`;mount.querySelector('[data-add]').addEventListener('click',()=>addToCart(p.id))}
function initCart(){const mount=document.querySelector('[data-cart]');if(!mount)return;function render(){const cart=getCart();const lines=cart.map(line=>({...PRODUCTS.find(p=>p.id===line.id),qty:line.qty}));if(!lines.length){mount.innerHTML='<div class="empty-cart"><h2>Your cart is empty.</h2><p>Find something good for your everyday.</p><a class="button dark-button" href="products.html">Browse all pieces <span>→</span></a></div>';return}const subtotal=lines.reduce((s,l)=>s+l.price*l.qty,0);mount.innerHTML=`<div class="cart-lines">${lines.map(l=>`<div class="cart-line"><img src="${l.image}" alt="${l.name}"><div class="cart-line-info"><p class="eyebrow">${l.category}</p><h2>${l.name}</h2><p>$${l.price.toFixed(2)}</p><div class="quantity"><button data-minus="${l.id}">−</button><span>${l.qty}</span><button data-plus="${l.id}">+</button><button class="remove-line" data-remove="${l.id}">Remove</button></div></div><strong>$${(l.price*l.qty).toFixed(2)}</strong></div>`).join('')}</div><aside class="cart-summary"><p class="eyebrow">YOUR SUMMARY</p><h2>Ready when you are.</h2><div class="summary-row"><span>Subtotal</span><strong>$${subtotal.toFixed(2)}</strong></div><div class="summary-row"><span>Shipping</span><strong>Free</strong></div><div class="summary-total"><span>Total</span><strong>$${subtotal.toFixed(2)}</strong></div><a class="button coral-button" href="checkout.html">Continue to checkout <span>→</span></a></aside>`;mount.querySelectorAll('[data-plus]').forEach(b=>b.onclick=()=>change(b.dataset.plus,1));mount.querySelectorAll('[data-minus]').forEach(b=>b.onclick=()=>change(b.dataset.minus,-1));mount.querySelectorAll('[data-remove]').forEach(b=>b.onclick=()=>{saveCart(getCart().filter(x=>x.id!==b.dataset.remove));render()})}function change(id,delta){const c=getCart();const l=c.find(x=>x.id===id);if(l)l.qty+=delta;saveCart(c.filter(x=>x.qty>0));render()}render()}
function initCheckout(){const form=document.querySelector('[data-checkout-form]');if(!form)return;form.addEventListener('submit',e=>{e.preventDefault();localStorage.removeItem('clothus-cart');document.querySelector('[data-checkout-shell]').innerHTML='<div class="order-confirmed"><div class="confirm-mark">✓</div><p class="eyebrow">THANK YOU</p><h1>Your order is<br><em>on its way.</em></h1><p>This is a demo checkout. No payment was taken, but your ClothUs order has been noted.</p><a class="button dark-button" href="index.html">Back home <span>→</span></a></div>';updateCartCount()})}
document.addEventListener('DOMContentLoaded',()=>{updateCartCount();initCatalog();initProduct();initCart();initCheckout()});
